In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [10]:
# Load dataset
df = pd.read_csv("/content/heart.csv")

# First 5 rows
print("First 5 rows")
print(df.head())

# Last 5 rows
print("\nLast 5 rows")
print(df.tail())

# Shape
print("\nDataset Shape")
print(df.shape)

# Info
print("\nDataset Information")
print(df.info())

First 5 rows
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0  

Last 5 rows
      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        

In [11]:
X = df.drop("target", axis=1)
y = df["target"]

print("Features (X)")
print(X)

print("\nTarget (y)")
print(y)

Features (X)
      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape")
print(X_train.shape)

print("Testing Data Shape")
print(X_test.shape)

Training Data Shape
(820, 13)
Testing Data Shape
(205, 13)


In [13]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!


In [14]:
predictions = model.predict(X_test)

print("First 10 Predicted Values")
print(predictions[:10])

print("\nFirst 10 Actual Values")
print(y_test.values[:10])

First 10 Predicted Values
[1 1 0 1 0 1 0 0 1 0]

First 10 Actual Values
[1 1 0 1 0 1 0 0 1 0]


In [15]:
new_data = pd.DataFrame({
    "age":[45,60,35],
    "sex":[1,0,1],
    "cp":[2,3,1],
    "trestbps":[130,140,120],
    "chol":[230,260,180],
    "fbs":[0,1,0],
    "restecg":[1,0,1],
    "thalach":[150,130,175],
    "exang":[0,1,0],
    "oldpeak":[1.2,2.5,0.5],
    "slope":[2,1,2],
    "ca":[0,2,0],
    "thal":[2,3,2]
})

prediction = model.predict(new_data)

print("Predictions for New Patients")
print(prediction)

Predictions for New Patients
[1 0 1]


In [16]:
print("------ SUMMARY ------")

print("Dataset Name: Heart Disease Dataset")
print("Number of Records:", df.shape[0])
print("Number of Features:", X.shape[1])
print("Target Column: target")
print("Model Used: Logistic Regression")

------ SUMMARY ------
Dataset Name: Heart Disease Dataset
Number of Records: 1025
Number of Features: 13
Target Column: target
Model Used: Logistic Regression
